staging-settings:                                                                                                                       
  user-workflow:                                                                                                                        
    workflow-name: "whitewall-access-staging" 
  workflow-artifacts:
    workflow-path: "."
    config-path: "./config.staging.json" 
    secrets-path: "./secrets.yaml" 
  

production-settings:
  user-workflow:
    workflow-name: "whitewall-access-production"
  workflow-artifacts:
    workflow-path: "."
    config-path: "./config.staging.json"
    secrets-path: "./secrets.yaml"

capabilities:
  - name: "evm-read"
  - name: "evm-write"
  - name: "report-encoder"
  - name: "confidential-http"

authorizedKeys:
  - "0x0d10F69243B8A2FE4299FA4cC115c3023F4011CF"